# Generated by Django 4.2.7 on 2023-11-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='csv',
            field=models.FileField(blank=True, upload_to='project_csvs/'),
        ),
    ]
